package wowjoy.fruits.ms.module.task.mapper;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import wowjoy.fruits.ms.module.task.FruitTask;
import wowjoy.fruits.ms.module.task.FruitTaskDao;
import wowjoy.fruits.ms.module.task.FruitTaskExample;

import java.util.List;

@Mapper
public interface FruitTaskMapper extends FruitTaskMapperExt{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_task
     *
     * @mbg.generated Fri Sep 08 15:25:06 CST 2017
     */
    long countByExample(FruitTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_task
     *
     * @mbg.generated Fri Sep 08 15:25:06 CST 2017
     */
    int deleteByExample(FruitTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_task
     *
     * @mbg.generated Fri Sep 08 15:25:06 CST 2017
     */
    int insert(FruitTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_task
     *
     * @mbg.generated Fri Sep 08 15:25:06 CST 2017
     */
    int insertSelective(FruitTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_task
     *
     * @mbg.generated Fri Sep 08 15:25:06 CST 2017
     */
    List<FruitTaskDao> selectByExample(FruitTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_task
     *
     * @mbg.generated Fri Sep 08 15:25:06 CST 2017
     */
    int updateByExampleSelective(@Param("record") FruitTask record, @Param("example") FruitTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_task
     *
     * @mbg.generated Fri Sep 08 15:25:06 CST 2017
     */
    int updateByExample(@Param("record") FruitTask record, @Param("example") FruitTaskExample example);
}