package wowjoy.fruits.ms.module.task.mapper;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import wowjoy.fruits.ms.module.task.example.TaskProjectRelationExample;
import wowjoy.fruits.ms.module.task.relation.TaskProjectRelation;

import java.util.List;
@Mapper
public interface TaskProjectRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_project_relation
     *
     * @mbg.generated Thu Aug 31 15:01:50 CST 2017
     */
    long countByExample(TaskProjectRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_project_relation
     *
     * @mbg.generated Thu Aug 31 15:01:50 CST 2017
     */
    int deleteByExample(TaskProjectRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_project_relation
     *
     * @mbg.generated Thu Aug 31 15:01:50 CST 2017
     */
    int insert(TaskProjectRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_project_relation
     *
     * @mbg.generated Thu Aug 31 15:01:50 CST 2017
     */
    int insertSelective(TaskProjectRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_project_relation
     *
     * @mbg.generated Thu Aug 31 15:01:50 CST 2017
     */
    List<TaskProjectRelation> selectByExample(TaskProjectRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_project_relation
     *
     * @mbg.generated Thu Aug 31 15:01:50 CST 2017
     */
    int updateByExampleSelective(@Param("record") TaskProjectRelation record, @Param("example") TaskProjectRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_project_relation
     *
     * @mbg.generated Thu Aug 31 15:01:50 CST 2017
     */
    int updateByExample(@Param("record") TaskProjectRelation record, @Param("example") TaskProjectRelationExample example);
}