package wowjoy.fruits.ms.module.task.mapper;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import wowjoy.fruits.ms.module.task.example.TaskTeamRelationExample;
import wowjoy.fruits.ms.module.task.relation.TaskTeamRelation;

import java.util.List;

@Mapper
public interface TaskTeamRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_team_relation
     *
     * @mbg.generated Thu Aug 31 15:01:50 CST 2017
     */
    long countByExample(TaskTeamRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_team_relation
     *
     * @mbg.generated Thu Aug 31 15:01:50 CST 2017
     */
    int deleteByExample(TaskTeamRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_team_relation
     *
     * @mbg.generated Thu Aug 31 15:01:50 CST 2017
     */
    int insert(TaskTeamRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_team_relation
     *
     * @mbg.generated Thu Aug 31 15:01:50 CST 2017
     */
    int insertSelective(TaskTeamRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_team_relation
     *
     * @mbg.generated Thu Aug 31 15:01:50 CST 2017
     */
    List<TaskTeamRelation> selectByExample(TaskTeamRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_team_relation
     *
     * @mbg.generated Thu Aug 31 15:01:50 CST 2017
     */
    int updateByExampleSelective(@Param("record") TaskTeamRelation record, @Param("example") TaskTeamRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_team_relation
     *
     * @mbg.generated Thu Aug 31 15:01:50 CST 2017
     */
    int updateByExample(@Param("record") TaskTeamRelation record, @Param("example") TaskTeamRelationExample example);
}