package wowjoy.fruits.ms.module.relation.entity;

import java.util.Date;

public class ProjectTeamRelation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_team_relation.uuid
     *
     * @mbg.generated Wed Sep 06 11:39:23 CST 2017
     */
    private String uuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_team_relation.project_id
     *
     * @mbg.generated Wed Sep 06 11:39:23 CST 2017
     */
    private String projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_team_relation.team_id
     *
     * @mbg.generated Wed Sep 06 11:39:23 CST 2017
     */
    private String teamId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_team_relation.tp_role
     *
     * @mbg.generated Wed Sep 06 11:39:23 CST 2017
     */
    private String tpRole;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_team_relation.description
     *
     * @mbg.generated Wed Sep 06 11:39:23 CST 2017
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_team_relation.modify_date_time
     *
     * @mbg.generated Wed Sep 06 11:39:23 CST 2017
     */
    private Date modifyDateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_team_relation.create_date_time
     *
     * @mbg.generated Wed Sep 06 11:39:23 CST 2017
     */
    private Date createDateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_team_relation.is_deleted
     *
     * @mbg.generated Wed Sep 06 11:39:23 CST 2017
     */
    private String isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_team_relation.uuid
     *
     * @return the value of project_team_relation.uuid
     *
     * @mbg.generated Wed Sep 06 11:39:23 CST 2017
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_team_relation.uuid
     *
     * @param uuid the value for project_team_relation.uuid
     *
     * @mbg.generated Wed Sep 06 11:39:23 CST 2017
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_team_relation.project_id
     *
     * @return the value of project_team_relation.project_id
     *
     * @mbg.generated Wed Sep 06 11:39:23 CST 2017
     */
    public String getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_team_relation.project_id
     *
     * @param projectId the value for project_team_relation.project_id
     *
     * @mbg.generated Wed Sep 06 11:39:23 CST 2017
     */
    public void setProjectId(String projectId) {
        this.projectId = projectId == null ? null : projectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_team_relation.team_id
     *
     * @return the value of project_team_relation.team_id
     *
     * @mbg.generated Wed Sep 06 11:39:23 CST 2017
     */
    public String getTeamId() {
        return teamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_team_relation.team_id
     *
     * @param teamId the value for project_team_relation.team_id
     *
     * @mbg.generated Wed Sep 06 11:39:23 CST 2017
     */
    public void setTeamId(String teamId) {
        this.teamId = teamId == null ? null : teamId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_team_relation.tp_role
     *
     * @return the value of project_team_relation.tp_role
     *
     * @mbg.generated Wed Sep 06 11:39:23 CST 2017
     */
    public String getTpRole() {
        return tpRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_team_relation.tp_role
     *
     * @param tpRole the value for project_team_relation.tp_role
     *
     * @mbg.generated Wed Sep 06 11:39:23 CST 2017
     */
    public void setTpRole(String tpRole) {
        this.tpRole = tpRole == null ? null : tpRole.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_team_relation.description
     *
     * @return the value of project_team_relation.description
     *
     * @mbg.generated Wed Sep 06 11:39:23 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_team_relation.description
     *
     * @param description the value for project_team_relation.description
     *
     * @mbg.generated Wed Sep 06 11:39:23 CST 2017
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_team_relation.modify_date_time
     *
     * @return the value of project_team_relation.modify_date_time
     *
     * @mbg.generated Wed Sep 06 11:39:23 CST 2017
     */
    public Date getModifyDateTime() {
        return modifyDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_team_relation.modify_date_time
     *
     * @param modifyDateTime the value for project_team_relation.modify_date_time
     *
     * @mbg.generated Wed Sep 06 11:39:23 CST 2017
     */
    public void setModifyDateTime(Date modifyDateTime) {
        this.modifyDateTime = modifyDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_team_relation.create_date_time
     *
     * @return the value of project_team_relation.create_date_time
     *
     * @mbg.generated Wed Sep 06 11:39:23 CST 2017
     */
    public Date getCreateDateTime() {
        return createDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_team_relation.create_date_time
     *
     * @param createDateTime the value for project_team_relation.create_date_time
     *
     * @mbg.generated Wed Sep 06 11:39:23 CST 2017
     */
    public void setCreateDateTime(Date createDateTime) {
        this.createDateTime = createDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_team_relation.is_deleted
     *
     * @return the value of project_team_relation.is_deleted
     *
     * @mbg.generated Wed Sep 06 11:39:23 CST 2017
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_team_relation.is_deleted
     *
     * @param isDeleted the value for project_team_relation.is_deleted
     *
     * @mbg.generated Wed Sep 06 11:39:23 CST 2017
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted == null ? null : isDeleted.trim();
    }
}