spring:
  application:
    name: ms-fruits
server:
  port: 9002
pagehelper:
  helper-dialect: mysql
  reasonable: true

security:
  user:
    password: password
  basic:
    enabled: false
#debug: true

tomcat:
  jdbc:
    pool:
      uri: jdbc:mysql://effiy.cn:3306/fruits?useUnicode=true&characterEncoding=utf8
      password: Yi19911024!@#
      username: root
      driverClassName: com.mysql.cj.jdbc.Driver
