spring:
  application:
    name: ms-fruits
server:
  port: 9002
pagehelper:
  helper-dialect: mysql
  reasonable: true

security:
  user:
    password: password
  basic:
    enabled: false
#debug: true