package wowjoy.fruits.ms.module.team.mapper;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import wowjoy.fruits.ms.module.team.FruitTeam;
import wowjoy.fruits.ms.module.team.FruitTeamDao;
import wowjoy.fruits.ms.module.team.FruitTeamExample;

import java.util.List;

@Mapper
public interface FruitTeamMapper extends FruitTeamMapperExt {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_team
     *
     * @mbg.generated Tue Sep 05 17:07:40 CST 2017
     */
    long countByExample(FruitTeamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_team
     *
     * @mbg.generated Tue Sep 05 17:07:40 CST 2017
     */
    int deleteByExample(FruitTeamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_team
     *
     * @mbg.generated Tue Sep 05 17:07:40 CST 2017
     */
    int insert(FruitTeam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_team
     *
     * @mbg.generated Tue Sep 05 17:07:40 CST 2017
     */
    int insertSelective(FruitTeam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_team
     *
     * @mbg.generated Tue Sep 05 17:07:40 CST 2017
     */
    List<FruitTeamDao> selectByExample(FruitTeamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_team
     *
     * @mbg.generated Tue Sep 05 17:07:40 CST 2017
     */
    int updateByExampleSelective(@Param("record") FruitTeam record, @Param("example") FruitTeamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_team
     *
     * @mbg.generated Tue Sep 05 17:07:40 CST 2017
     */
    int updateByExample(@Param("record") FruitTeam record, @Param("example") FruitTeamExample example);
}