package wowjoy.fruits.ms.module.defect;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class FruitDefectExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fruits_defect
     *
     * @mbg.generated Fri May 04 11:04:39 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fruits_defect
     *
     * @mbg.generated Fri May 04 11:04:39 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fruits_defect
     *
     * @mbg.generated Fri May 04 11:04:39 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_defect
     *
     * @mbg.generated Fri May 04 11:04:39 CST 2018
     */
    public FruitDefectExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_defect
     *
     * @mbg.generated Fri May 04 11:04:39 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_defect
     *
     * @mbg.generated Fri May 04 11:04:39 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_defect
     *
     * @mbg.generated Fri May 04 11:04:39 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_defect
     *
     * @mbg.generated Fri May 04 11:04:39 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_defect
     *
     * @mbg.generated Fri May 04 11:04:39 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_defect
     *
     * @mbg.generated Fri May 04 11:04:39 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_defect
     *
     * @mbg.generated Fri May 04 11:04:39 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_defect
     *
     * @mbg.generated Fri May 04 11:04:39 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_defect
     *
     * @mbg.generated Fri May 04 11:04:39 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_defect
     *
     * @mbg.generated Fri May 04 11:04:39 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fruits_defect
     *
     * @mbg.generated Fri May 04 11:04:39 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUuidIsNull() {
            addCriterion("uuid is null");
            return (Criteria) this;
        }

        public Criteria andUuidIsNotNull() {
            addCriterion("uuid is not null");
            return (Criteria) this;
        }

        public Criteria andUuidEqualTo(String value) {
            addCriterion("uuid =", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotEqualTo(String value) {
            addCriterion("uuid <>", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidGreaterThan(String value) {
            addCriterion("uuid >", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidGreaterThanOrEqualTo(String value) {
            addCriterion("uuid >=", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLessThan(String value) {
            addCriterion("uuid <", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLessThanOrEqualTo(String value) {
            addCriterion("uuid <=", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLike(String value) {
            addCriterion("uuid like", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotLike(String value) {
            addCriterion("uuid not like", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidIn(List<String> values) {
            addCriterion("uuid in", values, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotIn(List<String> values) {
            addCriterion("uuid not in", values, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidBetween(String value1, String value2) {
            addCriterion("uuid between", value1, value2, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotBetween(String value1, String value2) {
            addCriterion("uuid not between", value1, value2, "uuid");
            return (Criteria) this;
        }

        public Criteria andNumberIsNull() {
            addCriterion("number is null");
            return (Criteria) this;
        }

        public Criteria andNumberIsNotNull() {
            addCriterion("number is not null");
            return (Criteria) this;
        }

        public Criteria andNumberEqualTo(Integer value) {
            addCriterion("number =", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberNotEqualTo(Integer value) {
            addCriterion("number <>", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberGreaterThan(Integer value) {
            addCriterion("number >", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("number >=", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberLessThan(Integer value) {
            addCriterion("number <", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberLessThanOrEqualTo(Integer value) {
            addCriterion("number <=", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberIn(List<Integer> values) {
            addCriterion("number in", values, "number");
            return (Criteria) this;
        }

        public Criteria andNumberNotIn(List<Integer> values) {
            addCriterion("number not in", values, "number");
            return (Criteria) this;
        }

        public Criteria andNumberBetween(Integer value1, Integer value2) {
            addCriterion("number between", value1, value2, "number");
            return (Criteria) this;
        }

        public Criteria andNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("number not between", value1, value2, "number");
            return (Criteria) this;
        }

        public Criteria andProjectIdIsNull() {
            addCriterion("project_id is null");
            return (Criteria) this;
        }

        public Criteria andProjectIdIsNotNull() {
            addCriterion("project_id is not null");
            return (Criteria) this;
        }

        public Criteria andProjectIdEqualTo(String value) {
            addCriterion("project_id =", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotEqualTo(String value) {
            addCriterion("project_id <>", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThan(String value) {
            addCriterion("project_id >", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThanOrEqualTo(String value) {
            addCriterion("project_id >=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThan(String value) {
            addCriterion("project_id <", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThanOrEqualTo(String value) {
            addCriterion("project_id <=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLike(String value) {
            addCriterion("project_id like", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotLike(String value) {
            addCriterion("project_id not like", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdIn(List<String> values) {
            addCriterion("project_id in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotIn(List<String> values) {
            addCriterion("project_id not in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdBetween(String value1, String value2) {
            addCriterion("project_id between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotBetween(String value1, String value2) {
            addCriterion("project_id not between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andBeforeVersionIdIsNull() {
            addCriterion("before_version_id is null");
            return (Criteria) this;
        }

        public Criteria andBeforeVersionIdIsNotNull() {
            addCriterion("before_version_id is not null");
            return (Criteria) this;
        }

        public Criteria andBeforeVersionIdEqualTo(String value) {
            addCriterion("before_version_id =", value, "beforeVersionId");
            return (Criteria) this;
        }

        public Criteria andBeforeVersionIdNotEqualTo(String value) {
            addCriterion("before_version_id <>", value, "beforeVersionId");
            return (Criteria) this;
        }

        public Criteria andBeforeVersionIdGreaterThan(String value) {
            addCriterion("before_version_id >", value, "beforeVersionId");
            return (Criteria) this;
        }

        public Criteria andBeforeVersionIdGreaterThanOrEqualTo(String value) {
            addCriterion("before_version_id >=", value, "beforeVersionId");
            return (Criteria) this;
        }

        public Criteria andBeforeVersionIdLessThan(String value) {
            addCriterion("before_version_id <", value, "beforeVersionId");
            return (Criteria) this;
        }

        public Criteria andBeforeVersionIdLessThanOrEqualTo(String value) {
            addCriterion("before_version_id <=", value, "beforeVersionId");
            return (Criteria) this;
        }

        public Criteria andBeforeVersionIdLike(String value) {
            addCriterion("before_version_id like", value, "beforeVersionId");
            return (Criteria) this;
        }

        public Criteria andBeforeVersionIdNotLike(String value) {
            addCriterion("before_version_id not like", value, "beforeVersionId");
            return (Criteria) this;
        }

        public Criteria andBeforeVersionIdIn(List<String> values) {
            addCriterion("before_version_id in", values, "beforeVersionId");
            return (Criteria) this;
        }

        public Criteria andBeforeVersionIdNotIn(List<String> values) {
            addCriterion("before_version_id not in", values, "beforeVersionId");
            return (Criteria) this;
        }

        public Criteria andBeforeVersionIdBetween(String value1, String value2) {
            addCriterion("before_version_id between", value1, value2, "beforeVersionId");
            return (Criteria) this;
        }

        public Criteria andBeforeVersionIdNotBetween(String value1, String value2) {
            addCriterion("before_version_id not between", value1, value2, "beforeVersionId");
            return (Criteria) this;
        }

        public Criteria andAfterVersionIdIsNull() {
            addCriterion("after_version_id is null");
            return (Criteria) this;
        }

        public Criteria andAfterVersionIdIsNotNull() {
            addCriterion("after_version_id is not null");
            return (Criteria) this;
        }

        public Criteria andAfterVersionIdEqualTo(String value) {
            addCriterion("after_version_id =", value, "afterVersionId");
            return (Criteria) this;
        }

        public Criteria andAfterVersionIdNotEqualTo(String value) {
            addCriterion("after_version_id <>", value, "afterVersionId");
            return (Criteria) this;
        }

        public Criteria andAfterVersionIdGreaterThan(String value) {
            addCriterion("after_version_id >", value, "afterVersionId");
            return (Criteria) this;
        }

        public Criteria andAfterVersionIdGreaterThanOrEqualTo(String value) {
            addCriterion("after_version_id >=", value, "afterVersionId");
            return (Criteria) this;
        }

        public Criteria andAfterVersionIdLessThan(String value) {
            addCriterion("after_version_id <", value, "afterVersionId");
            return (Criteria) this;
        }

        public Criteria andAfterVersionIdLessThanOrEqualTo(String value) {
            addCriterion("after_version_id <=", value, "afterVersionId");
            return (Criteria) this;
        }

        public Criteria andAfterVersionIdLike(String value) {
            addCriterion("after_version_id like", value, "afterVersionId");
            return (Criteria) this;
        }

        public Criteria andAfterVersionIdNotLike(String value) {
            addCriterion("after_version_id not like", value, "afterVersionId");
            return (Criteria) this;
        }

        public Criteria andAfterVersionIdIn(List<String> values) {
            addCriterion("after_version_id in", values, "afterVersionId");
            return (Criteria) this;
        }

        public Criteria andAfterVersionIdNotIn(List<String> values) {
            addCriterion("after_version_id not in", values, "afterVersionId");
            return (Criteria) this;
        }

        public Criteria andAfterVersionIdBetween(String value1, String value2) {
            addCriterion("after_version_id between", value1, value2, "afterVersionId");
            return (Criteria) this;
        }

        public Criteria andAfterVersionIdNotBetween(String value1, String value2) {
            addCriterion("after_version_id not between", value1, value2, "afterVersionId");
            return (Criteria) this;
        }

        public Criteria andDefectNameIsNull() {
            addCriterion("defect_name is null");
            return (Criteria) this;
        }

        public Criteria andDefectNameIsNotNull() {
            addCriterion("defect_name is not null");
            return (Criteria) this;
        }

        public Criteria andDefectNameEqualTo(String value) {
            addCriterion("defect_name =", value, "defectName");
            return (Criteria) this;
        }

        public Criteria andDefectNameNotEqualTo(String value) {
            addCriterion("defect_name <>", value, "defectName");
            return (Criteria) this;
        }

        public Criteria andDefectNameGreaterThan(String value) {
            addCriterion("defect_name >", value, "defectName");
            return (Criteria) this;
        }

        public Criteria andDefectNameGreaterThanOrEqualTo(String value) {
            addCriterion("defect_name >=", value, "defectName");
            return (Criteria) this;
        }

        public Criteria andDefectNameLessThan(String value) {
            addCriterion("defect_name <", value, "defectName");
            return (Criteria) this;
        }

        public Criteria andDefectNameLessThanOrEqualTo(String value) {
            addCriterion("defect_name <=", value, "defectName");
            return (Criteria) this;
        }

        public Criteria andDefectNameLike(String value) {
            addCriterion("defect_name like", value, "defectName");
            return (Criteria) this;
        }

        public Criteria andDefectNameNotLike(String value) {
            addCriterion("defect_name not like", value, "defectName");
            return (Criteria) this;
        }

        public Criteria andDefectNameIn(List<String> values) {
            addCriterion("defect_name in", values, "defectName");
            return (Criteria) this;
        }

        public Criteria andDefectNameNotIn(List<String> values) {
            addCriterion("defect_name not in", values, "defectName");
            return (Criteria) this;
        }

        public Criteria andDefectNameBetween(String value1, String value2) {
            addCriterion("defect_name between", value1, value2, "defectName");
            return (Criteria) this;
        }

        public Criteria andDefectNameNotBetween(String value1, String value2) {
            addCriterion("defect_name not between", value1, value2, "defectName");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("user_id like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("user_id not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andHandlerUserIdIsNull() {
            addCriterion("handler_user_id is null");
            return (Criteria) this;
        }

        public Criteria andHandlerUserIdIsNotNull() {
            addCriterion("handler_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andHandlerUserIdEqualTo(String value) {
            addCriterion("handler_user_id =", value, "handlerUserId");
            return (Criteria) this;
        }

        public Criteria andHandlerUserIdNotEqualTo(String value) {
            addCriterion("handler_user_id <>", value, "handlerUserId");
            return (Criteria) this;
        }

        public Criteria andHandlerUserIdGreaterThan(String value) {
            addCriterion("handler_user_id >", value, "handlerUserId");
            return (Criteria) this;
        }

        public Criteria andHandlerUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("handler_user_id >=", value, "handlerUserId");
            return (Criteria) this;
        }

        public Criteria andHandlerUserIdLessThan(String value) {
            addCriterion("handler_user_id <", value, "handlerUserId");
            return (Criteria) this;
        }

        public Criteria andHandlerUserIdLessThanOrEqualTo(String value) {
            addCriterion("handler_user_id <=", value, "handlerUserId");
            return (Criteria) this;
        }

        public Criteria andHandlerUserIdLike(String value) {
            addCriterion("handler_user_id like", value, "handlerUserId");
            return (Criteria) this;
        }

        public Criteria andHandlerUserIdNotLike(String value) {
            addCriterion("handler_user_id not like", value, "handlerUserId");
            return (Criteria) this;
        }

        public Criteria andHandlerUserIdIn(List<String> values) {
            addCriterion("handler_user_id in", values, "handlerUserId");
            return (Criteria) this;
        }

        public Criteria andHandlerUserIdNotIn(List<String> values) {
            addCriterion("handler_user_id not in", values, "handlerUserId");
            return (Criteria) this;
        }

        public Criteria andHandlerUserIdBetween(String value1, String value2) {
            addCriterion("handler_user_id between", value1, value2, "handlerUserId");
            return (Criteria) this;
        }

        public Criteria andHandlerUserIdNotBetween(String value1, String value2) {
            addCriterion("handler_user_id not between", value1, value2, "handlerUserId");
            return (Criteria) this;
        }

        public Criteria andDefectTypeIsNull() {
            addCriterion("defect_type is null");
            return (Criteria) this;
        }

        public Criteria andDefectTypeIsNotNull() {
            addCriterion("defect_type is not null");
            return (Criteria) this;
        }

        public Criteria andDefectTypeEqualTo(String value) {
            addCriterion("defect_type =", value, "defectType");
            return (Criteria) this;
        }

        public Criteria andDefectTypeNotEqualTo(String value) {
            addCriterion("defect_type <>", value, "defectType");
            return (Criteria) this;
        }

        public Criteria andDefectTypeGreaterThan(String value) {
            addCriterion("defect_type >", value, "defectType");
            return (Criteria) this;
        }

        public Criteria andDefectTypeGreaterThanOrEqualTo(String value) {
            addCriterion("defect_type >=", value, "defectType");
            return (Criteria) this;
        }

        public Criteria andDefectTypeLessThan(String value) {
            addCriterion("defect_type <", value, "defectType");
            return (Criteria) this;
        }

        public Criteria andDefectTypeLessThanOrEqualTo(String value) {
            addCriterion("defect_type <=", value, "defectType");
            return (Criteria) this;
        }

        public Criteria andDefectTypeLike(String value) {
            addCriterion("defect_type like", value, "defectType");
            return (Criteria) this;
        }

        public Criteria andDefectTypeNotLike(String value) {
            addCriterion("defect_type not like", value, "defectType");
            return (Criteria) this;
        }

        public Criteria andDefectTypeIn(List<String> values) {
            addCriterion("defect_type in", values, "defectType");
            return (Criteria) this;
        }

        public Criteria andDefectTypeNotIn(List<String> values) {
            addCriterion("defect_type not in", values, "defectType");
            return (Criteria) this;
        }

        public Criteria andDefectTypeBetween(String value1, String value2) {
            addCriterion("defect_type between", value1, value2, "defectType");
            return (Criteria) this;
        }

        public Criteria andDefectTypeNotBetween(String value1, String value2) {
            addCriterion("defect_type not between", value1, value2, "defectType");
            return (Criteria) this;
        }

        public Criteria andDefectLevelIsNull() {
            addCriterion("defect_level is null");
            return (Criteria) this;
        }

        public Criteria andDefectLevelIsNotNull() {
            addCriterion("defect_level is not null");
            return (Criteria) this;
        }

        public Criteria andDefectLevelEqualTo(String value) {
            addCriterion("defect_level =", value, "defectLevel");
            return (Criteria) this;
        }

        public Criteria andDefectLevelNotEqualTo(String value) {
            addCriterion("defect_level <>", value, "defectLevel");
            return (Criteria) this;
        }

        public Criteria andDefectLevelGreaterThan(String value) {
            addCriterion("defect_level >", value, "defectLevel");
            return (Criteria) this;
        }

        public Criteria andDefectLevelGreaterThanOrEqualTo(String value) {
            addCriterion("defect_level >=", value, "defectLevel");
            return (Criteria) this;
        }

        public Criteria andDefectLevelLessThan(String value) {
            addCriterion("defect_level <", value, "defectLevel");
            return (Criteria) this;
        }

        public Criteria andDefectLevelLessThanOrEqualTo(String value) {
            addCriterion("defect_level <=", value, "defectLevel");
            return (Criteria) this;
        }

        public Criteria andDefectLevelLike(String value) {
            addCriterion("defect_level like", value, "defectLevel");
            return (Criteria) this;
        }

        public Criteria andDefectLevelNotLike(String value) {
            addCriterion("defect_level not like", value, "defectLevel");
            return (Criteria) this;
        }

        public Criteria andDefectLevelIn(List<String> values) {
            addCriterion("defect_level in", values, "defectLevel");
            return (Criteria) this;
        }

        public Criteria andDefectLevelNotIn(List<String> values) {
            addCriterion("defect_level not in", values, "defectLevel");
            return (Criteria) this;
        }

        public Criteria andDefectLevelBetween(String value1, String value2) {
            addCriterion("defect_level between", value1, value2, "defectLevel");
            return (Criteria) this;
        }

        public Criteria andDefectLevelNotBetween(String value1, String value2) {
            addCriterion("defect_level not between", value1, value2, "defectLevel");
            return (Criteria) this;
        }

        public Criteria andRiskIndexIsNull() {
            addCriterion("risk_index is null");
            return (Criteria) this;
        }

        public Criteria andRiskIndexIsNotNull() {
            addCriterion("risk_index is not null");
            return (Criteria) this;
        }

        public Criteria andRiskIndexEqualTo(String value) {
            addCriterion("risk_index =", value, "riskIndex");
            return (Criteria) this;
        }

        public Criteria andRiskIndexNotEqualTo(String value) {
            addCriterion("risk_index <>", value, "riskIndex");
            return (Criteria) this;
        }

        public Criteria andRiskIndexGreaterThan(String value) {
            addCriterion("risk_index >", value, "riskIndex");
            return (Criteria) this;
        }

        public Criteria andRiskIndexGreaterThanOrEqualTo(String value) {
            addCriterion("risk_index >=", value, "riskIndex");
            return (Criteria) this;
        }

        public Criteria andRiskIndexLessThan(String value) {
            addCriterion("risk_index <", value, "riskIndex");
            return (Criteria) this;
        }

        public Criteria andRiskIndexLessThanOrEqualTo(String value) {
            addCriterion("risk_index <=", value, "riskIndex");
            return (Criteria) this;
        }

        public Criteria andRiskIndexLike(String value) {
            addCriterion("risk_index like", value, "riskIndex");
            return (Criteria) this;
        }

        public Criteria andRiskIndexNotLike(String value) {
            addCriterion("risk_index not like", value, "riskIndex");
            return (Criteria) this;
        }

        public Criteria andRiskIndexIn(List<String> values) {
            addCriterion("risk_index in", values, "riskIndex");
            return (Criteria) this;
        }

        public Criteria andRiskIndexNotIn(List<String> values) {
            addCriterion("risk_index not in", values, "riskIndex");
            return (Criteria) this;
        }

        public Criteria andRiskIndexBetween(String value1, String value2) {
            addCriterion("risk_index between", value1, value2, "riskIndex");
            return (Criteria) this;
        }

        public Criteria andRiskIndexNotBetween(String value1, String value2) {
            addCriterion("risk_index not between", value1, value2, "riskIndex");
            return (Criteria) this;
        }

        public Criteria andDefectStatusIsNull() {
            addCriterion("defect_status is null");
            return (Criteria) this;
        }

        public Criteria andDefectStatusIsNotNull() {
            addCriterion("defect_status is not null");
            return (Criteria) this;
        }

        public Criteria andDefectStatusEqualTo(String value) {
            addCriterion("defect_status =", value, "defectStatus");
            return (Criteria) this;
        }

        public Criteria andDefectStatusNotEqualTo(String value) {
            addCriterion("defect_status <>", value, "defectStatus");
            return (Criteria) this;
        }

        public Criteria andDefectStatusGreaterThan(String value) {
            addCriterion("defect_status >", value, "defectStatus");
            return (Criteria) this;
        }

        public Criteria andDefectStatusGreaterThanOrEqualTo(String value) {
            addCriterion("defect_status >=", value, "defectStatus");
            return (Criteria) this;
        }

        public Criteria andDefectStatusLessThan(String value) {
            addCriterion("defect_status <", value, "defectStatus");
            return (Criteria) this;
        }

        public Criteria andDefectStatusLessThanOrEqualTo(String value) {
            addCriterion("defect_status <=", value, "defectStatus");
            return (Criteria) this;
        }

        public Criteria andDefectStatusLike(String value) {
            addCriterion("defect_status like", value, "defectStatus");
            return (Criteria) this;
        }

        public Criteria andDefectStatusNotLike(String value) {
            addCriterion("defect_status not like", value, "defectStatus");
            return (Criteria) this;
        }

        public Criteria andDefectStatusIn(List<String> values) {
            addCriterion("defect_status in", values, "defectStatus");
            return (Criteria) this;
        }

        public Criteria andDefectStatusNotIn(List<String> values) {
            addCriterion("defect_status not in", values, "defectStatus");
            return (Criteria) this;
        }

        public Criteria andDefectStatusBetween(String value1, String value2) {
            addCriterion("defect_status between", value1, value2, "defectStatus");
            return (Criteria) this;
        }

        public Criteria andDefectStatusNotBetween(String value1, String value2) {
            addCriterion("defect_status not between", value1, value2, "defectStatus");
            return (Criteria) this;
        }

        public Criteria andEndDateTimeIsNull() {
            addCriterion("end_date_time is null");
            return (Criteria) this;
        }

        public Criteria andEndDateTimeIsNotNull() {
            addCriterion("end_date_time is not null");
            return (Criteria) this;
        }

        public Criteria andEndDateTimeEqualTo(Date value) {
            addCriterion("end_date_time =", value, "endDateTime");
            return (Criteria) this;
        }

        public Criteria andEndDateTimeNotEqualTo(Date value) {
            addCriterion("end_date_time <>", value, "endDateTime");
            return (Criteria) this;
        }

        public Criteria andEndDateTimeGreaterThan(Date value) {
            addCriterion("end_date_time >", value, "endDateTime");
            return (Criteria) this;
        }

        public Criteria andEndDateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("end_date_time >=", value, "endDateTime");
            return (Criteria) this;
        }

        public Criteria andEndDateTimeLessThan(Date value) {
            addCriterion("end_date_time <", value, "endDateTime");
            return (Criteria) this;
        }

        public Criteria andEndDateTimeLessThanOrEqualTo(Date value) {
            addCriterion("end_date_time <=", value, "endDateTime");
            return (Criteria) this;
        }

        public Criteria andEndDateTimeIn(List<Date> values) {
            addCriterion("end_date_time in", values, "endDateTime");
            return (Criteria) this;
        }

        public Criteria andEndDateTimeNotIn(List<Date> values) {
            addCriterion("end_date_time not in", values, "endDateTime");
            return (Criteria) this;
        }

        public Criteria andEndDateTimeBetween(Date value1, Date value2) {
            addCriterion("end_date_time between", value1, value2, "endDateTime");
            return (Criteria) this;
        }

        public Criteria andEndDateTimeNotBetween(Date value1, Date value2) {
            addCriterion("end_date_time not between", value1, value2, "endDateTime");
            return (Criteria) this;
        }

        public Criteria andDuplicateIsNull() {
            addCriterion("duplicate is null");
            return (Criteria) this;
        }

        public Criteria andDuplicateIsNotNull() {
            addCriterion("duplicate is not null");
            return (Criteria) this;
        }

        public Criteria andDuplicateEqualTo(String value) {
            addCriterion("duplicate =", value, "duplicate");
            return (Criteria) this;
        }

        public Criteria andDuplicateNotEqualTo(String value) {
            addCriterion("duplicate <>", value, "duplicate");
            return (Criteria) this;
        }

        public Criteria andDuplicateGreaterThan(String value) {
            addCriterion("duplicate >", value, "duplicate");
            return (Criteria) this;
        }

        public Criteria andDuplicateGreaterThanOrEqualTo(String value) {
            addCriterion("duplicate >=", value, "duplicate");
            return (Criteria) this;
        }

        public Criteria andDuplicateLessThan(String value) {
            addCriterion("duplicate <", value, "duplicate");
            return (Criteria) this;
        }

        public Criteria andDuplicateLessThanOrEqualTo(String value) {
            addCriterion("duplicate <=", value, "duplicate");
            return (Criteria) this;
        }

        public Criteria andDuplicateLike(String value) {
            addCriterion("duplicate like", value, "duplicate");
            return (Criteria) this;
        }

        public Criteria andDuplicateNotLike(String value) {
            addCriterion("duplicate not like", value, "duplicate");
            return (Criteria) this;
        }

        public Criteria andDuplicateIn(List<String> values) {
            addCriterion("duplicate in", values, "duplicate");
            return (Criteria) this;
        }

        public Criteria andDuplicateNotIn(List<String> values) {
            addCriterion("duplicate not in", values, "duplicate");
            return (Criteria) this;
        }

        public Criteria andDuplicateBetween(String value1, String value2) {
            addCriterion("duplicate between", value1, value2, "duplicate");
            return (Criteria) this;
        }

        public Criteria andDuplicateNotBetween(String value1, String value2) {
            addCriterion("duplicate not between", value1, value2, "duplicate");
            return (Criteria) this;
        }

        public Criteria andModifyDateTimeIsNull() {
            addCriterion("modify_date_time is null");
            return (Criteria) this;
        }

        public Criteria andModifyDateTimeIsNotNull() {
            addCriterion("modify_date_time is not null");
            return (Criteria) this;
        }

        public Criteria andModifyDateTimeEqualTo(Date value) {
            addCriterion("modify_date_time =", value, "modifyDateTime");
            return (Criteria) this;
        }

        public Criteria andModifyDateTimeNotEqualTo(Date value) {
            addCriterion("modify_date_time <>", value, "modifyDateTime");
            return (Criteria) this;
        }

        public Criteria andModifyDateTimeGreaterThan(Date value) {
            addCriterion("modify_date_time >", value, "modifyDateTime");
            return (Criteria) this;
        }

        public Criteria andModifyDateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("modify_date_time >=", value, "modifyDateTime");
            return (Criteria) this;
        }

        public Criteria andModifyDateTimeLessThan(Date value) {
            addCriterion("modify_date_time <", value, "modifyDateTime");
            return (Criteria) this;
        }

        public Criteria andModifyDateTimeLessThanOrEqualTo(Date value) {
            addCriterion("modify_date_time <=", value, "modifyDateTime");
            return (Criteria) this;
        }

        public Criteria andModifyDateTimeIn(List<Date> values) {
            addCriterion("modify_date_time in", values, "modifyDateTime");
            return (Criteria) this;
        }

        public Criteria andModifyDateTimeNotIn(List<Date> values) {
            addCriterion("modify_date_time not in", values, "modifyDateTime");
            return (Criteria) this;
        }

        public Criteria andModifyDateTimeBetween(Date value1, Date value2) {
            addCriterion("modify_date_time between", value1, value2, "modifyDateTime");
            return (Criteria) this;
        }

        public Criteria andModifyDateTimeNotBetween(Date value1, Date value2) {
            addCriterion("modify_date_time not between", value1, value2, "modifyDateTime");
            return (Criteria) this;
        }

        public Criteria andCreateDateTimeIsNull() {
            addCriterion("create_date_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateTimeIsNotNull() {
            addCriterion("create_date_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateTimeEqualTo(Date value) {
            addCriterion("create_date_time =", value, "createDateTime");
            return (Criteria) this;
        }

        public Criteria andCreateDateTimeNotEqualTo(Date value) {
            addCriterion("create_date_time <>", value, "createDateTime");
            return (Criteria) this;
        }

        public Criteria andCreateDateTimeGreaterThan(Date value) {
            addCriterion("create_date_time >", value, "createDateTime");
            return (Criteria) this;
        }

        public Criteria andCreateDateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_date_time >=", value, "createDateTime");
            return (Criteria) this;
        }

        public Criteria andCreateDateTimeLessThan(Date value) {
            addCriterion("create_date_time <", value, "createDateTime");
            return (Criteria) this;
        }

        public Criteria andCreateDateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_date_time <=", value, "createDateTime");
            return (Criteria) this;
        }

        public Criteria andCreateDateTimeIn(List<Date> values) {
            addCriterion("create_date_time in", values, "createDateTime");
            return (Criteria) this;
        }

        public Criteria andCreateDateTimeNotIn(List<Date> values) {
            addCriterion("create_date_time not in", values, "createDateTime");
            return (Criteria) this;
        }

        public Criteria andCreateDateTimeBetween(Date value1, Date value2) {
            addCriterion("create_date_time between", value1, value2, "createDateTime");
            return (Criteria) this;
        }

        public Criteria andCreateDateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_date_time not between", value1, value2, "createDateTime");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIsNull() {
            addCriterion("is_deleted is null");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIsNotNull() {
            addCriterion("is_deleted is not null");
            return (Criteria) this;
        }

        public Criteria andIsDeletedEqualTo(String value) {
            addCriterion("is_deleted =", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotEqualTo(String value) {
            addCriterion("is_deleted <>", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedGreaterThan(String value) {
            addCriterion("is_deleted >", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedGreaterThanOrEqualTo(String value) {
            addCriterion("is_deleted >=", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedLessThan(String value) {
            addCriterion("is_deleted <", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedLessThanOrEqualTo(String value) {
            addCriterion("is_deleted <=", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedLike(String value) {
            addCriterion("is_deleted like", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotLike(String value) {
            addCriterion("is_deleted not like", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIn(List<String> values) {
            addCriterion("is_deleted in", values, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotIn(List<String> values) {
            addCriterion("is_deleted not in", values, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedBetween(String value1, String value2) {
            addCriterion("is_deleted between", value1, value2, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotBetween(String value1, String value2) {
            addCriterion("is_deleted not between", value1, value2, "isDeleted");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fruits_defect
     *
     * @mbg.generated do_not_delete_during_merge Fri May 04 11:04:39 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fruits_defect
     *
     * @mbg.generated Fri May 04 11:04:39 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}