package wowjoy.fruits.ms.module.resource.mapper;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import wowjoy.fruits.ms.module.resource.FruitResource;
import wowjoy.fruits.ms.module.resource.FruitResourceExample;

import java.util.List;

@Mapper
public interface FruitResourceMapper extends FruitResourceMapperExt {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_resource
     *
     * @mbg.generated Sun Apr 08 10:37:29 CST 2018
     */
    long countByExample(FruitResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_resource
     *
     * @mbg.generated Sun Apr 08 10:37:29 CST 2018
     */
    int deleteByExample(FruitResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_resource
     *
     * @mbg.generated Sun Apr 08 10:37:29 CST 2018
     */
    int insert(FruitResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_resource
     *
     * @mbg.generated Sun Apr 08 10:37:29 CST 2018
     */
    int insertSelective(FruitResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_resource
     *
     * @mbg.generated Sun Apr 08 10:37:29 CST 2018
     */
    List<FruitResource> selectByExample(FruitResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_resource
     *
     * @mbg.generated Sun Apr 08 10:37:29 CST 2018
     */
    int updateByExampleSelective(@Param("record") FruitResource record, @Param("example") FruitResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_resource
     *
     * @mbg.generated Sun Apr 08 10:37:29 CST 2018
     */
    int updateByExample(@Param("record") FruitResource record, @Param("example") FruitResourceExample example);
}