package wowjoy.fruits.ms.module.list.mapper;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import wowjoy.fruits.ms.module.list.FruitList;
import wowjoy.fruits.ms.module.list.FruitListDao;
import wowjoy.fruits.ms.module.list.FruitListExample;

import java.util.List;

@Mapper
public interface FruitListMapper extends FruitListMapperExt {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_list
     *
     * @mbg.generated Tue Oct 17 11:05:50 CST 2017
     */
    long countByExample(FruitListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_list
     *
     * @mbg.generated Tue Oct 17 11:05:50 CST 2017
     */
    int deleteByExample(FruitListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_list
     *
     * @mbg.generated Tue Oct 17 11:05:50 CST 2017
     */
    int insert(FruitList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_list
     *
     * @mbg.generated Tue Oct 17 11:05:50 CST 2017
     */
    int insertSelective(FruitList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_list
     *
     * @mbg.generated Tue Oct 17 11:05:50 CST 2017
     */
    List<FruitListDao> selectByExample(FruitListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_list
     *
     * @mbg.generated Tue Oct 17 11:05:50 CST 2017
     */
    int updateByExampleSelective(@Param("record") FruitList record, @Param("example") FruitListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_list
     *
     * @mbg.generated Tue Oct 17 11:05:50 CST 2017
     */
    int updateByExample(@Param("record") FruitList record, @Param("example") FruitListExample example);
}