package wowjoy.fruits.ms.module.logs.mapper;

import org.apache.ibatis.annotations.Param;
import wowjoy.fruits.ms.module.logs.FruitLogs;
import wowjoy.fruits.ms.module.logs.FruitLogsExample;

import java.util.List;

public interface FruitLogsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_logs
     *
     * @mbg.generated Wed Dec 06 13:59:11 CST 2017
     */
    long countByExample(FruitLogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_logs
     *
     * @mbg.generated Wed Dec 06 13:59:11 CST 2017
     */
    int deleteByExample(FruitLogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_logs
     *
     * @mbg.generated Wed Dec 06 13:59:11 CST 2017
     */
    int insert(FruitLogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_logs
     *
     * @mbg.generated Wed Dec 06 13:59:11 CST 2017
     */
    int insertSelective(FruitLogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_logs
     *
     * @mbg.generated Wed Dec 06 13:59:11 CST 2017
     */
    List<FruitLogs> selectByExampleWithBLOBs(FruitLogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_logs
     *
     * @mbg.generated Wed Dec 06 13:59:11 CST 2017
     */
    List<FruitLogs> selectByExample(FruitLogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_logs
     *
     * @mbg.generated Wed Dec 06 13:59:11 CST 2017
     */
    int updateByExampleSelective(@Param("record") FruitLogs record, @Param("example") FruitLogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_logs
     *
     * @mbg.generated Wed Dec 06 13:59:11 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") FruitLogs record, @Param("example") FruitLogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_logs
     *
     * @mbg.generated Wed Dec 06 13:59:11 CST 2017
     */
    int updateByExample(@Param("record") FruitLogs record, @Param("example") FruitLogsExample example);
}