package wowjoy.fruits.ms.module.project.mapper;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import wowjoy.fruits.ms.module.project.FruitProject;
import wowjoy.fruits.ms.module.project.FruitProjectExample;

import java.util.List;

@Mapper
public interface FruitProjectMapper extends FruitProjectMapperExt{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_project
     *
     * @mbg.generated Wed Sep 06 11:36:15 CST 2017
     */
    long countByExample(FruitProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_project
     *
     * @mbg.generated Wed Sep 06 11:36:15 CST 2017
     */
    int deleteByExample(FruitProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_project
     *
     * @mbg.generated Wed Sep 06 11:36:15 CST 2017
     */
    int insert(FruitProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_project
     *
     * @mbg.generated Wed Sep 06 11:36:15 CST 2017
     */
    int insertSelective(FruitProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_project
     *
     * @mbg.generated Wed Sep 06 11:36:15 CST 2017
     */
    List<FruitProject> selectByExample(FruitProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_project
     *
     * @mbg.generated Wed Sep 06 11:36:15 CST 2017
     */
    int updateByExampleSelective(@Param("record") FruitProject record, @Param("example") FruitProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_project
     *
     * @mbg.generated Wed Sep 06 11:36:15 CST 2017
     */
    int updateByExample(@Param("record") FruitProject record, @Param("example") FruitProjectExample example);
}