package wowjoy.fruits.ms.module.notepad.mapper;

import org.apache.ibatis.annotations.Param;
import wowjoy.fruits.ms.module.notepad.FruitNotepad;
import wowjoy.fruits.ms.module.notepad.FruitNotepadDao;
import wowjoy.fruits.ms.module.notepad.FruitNotepadExample;

import java.util.List;

public interface FruitNotepadMapper extends FruitNotepadMapperExt{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_notepad
     *
     * @mbg.generated Tue Mar 06 14:15:09 CST 2018
     */
    long countByExample(FruitNotepadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_notepad
     *
     * @mbg.generated Tue Mar 06 14:15:09 CST 2018
     */
    int deleteByExample(FruitNotepadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_notepad
     *
     * @mbg.generated Tue Mar 06 14:15:09 CST 2018
     */
    int insert(FruitNotepad record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_notepad
     *
     * @mbg.generated Tue Mar 06 14:15:09 CST 2018
     */
    int insertSelective(FruitNotepad record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_notepad
     *
     * @mbg.generated Tue Mar 06 14:15:09 CST 2018
     */
    List<FruitNotepad> selectByExampleWithBLOBs(FruitNotepadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_notepad
     *
     * @mbg.generated Tue Mar 06 14:15:09 CST 2018
     */
    List<FruitNotepadDao> selectByExample(FruitNotepadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_notepad
     *
     * @mbg.generated Tue Mar 06 14:15:09 CST 2018
     */
    int updateByExampleSelective(@Param("record") FruitNotepad record, @Param("example") FruitNotepadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_notepad
     *
     * @mbg.generated Tue Mar 06 14:15:09 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") FruitNotepad record, @Param("example") FruitNotepadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_notepad
     *
     * @mbg.generated Tue Mar 06 14:15:09 CST 2018
     */
    int updateByExample(@Param("record") FruitNotepad record, @Param("example") FruitNotepadExample example);
}