package wowjoy.fruits.ms.module.relation.mapper;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import wowjoy.fruits.ms.module.relation.entity.DefectCommentRelation;
import wowjoy.fruits.ms.module.relation.example.DefectCommentRelationExample;

import java.util.List;

@Mapper
public interface DefectCommentRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defect_comment_relation
     *
     * @mbg.generated Fri May 04 14:54:20 CST 2018
     */
    long countByExample(DefectCommentRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defect_comment_relation
     *
     * @mbg.generated Fri May 04 14:54:20 CST 2018
     */
    int deleteByExample(DefectCommentRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defect_comment_relation
     *
     * @mbg.generated Fri May 04 14:54:20 CST 2018
     */
    int insert(DefectCommentRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defect_comment_relation
     *
     * @mbg.generated Fri May 04 14:54:20 CST 2018
     */
    int insertSelective(DefectCommentRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defect_comment_relation
     *
     * @mbg.generated Fri May 04 14:54:20 CST 2018
     */
    List<DefectCommentRelation> selectByExample(DefectCommentRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defect_comment_relation
     *
     * @mbg.generated Fri May 04 14:54:20 CST 2018
     */
    int updateByExampleSelective(@Param("record") DefectCommentRelation record, @Param("example") DefectCommentRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defect_comment_relation
     *
     * @mbg.generated Fri May 04 14:54:20 CST 2018
     */
    int updateByExample(@Param("record") DefectCommentRelation record, @Param("example") DefectCommentRelationExample example);
}