package wowjoy.fruits.ms.module.relation.mapper;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import wowjoy.fruits.ms.module.relation.entity.DefectResourceRelation;
import wowjoy.fruits.ms.module.relation.example.DefectResourceRelationExample;

import java.util.List;

@Mapper
public interface DefectResourceRelationMapper extends DefectResourceRelationMapperExt{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defect_resource_relation
     *
     * @mbg.generated Mon Apr 23 10:23:22 CST 2018
     */
    long countByExample(DefectResourceRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defect_resource_relation
     *
     * @mbg.generated Mon Apr 23 10:23:22 CST 2018
     */
    int deleteByExample(DefectResourceRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defect_resource_relation
     *
     * @mbg.generated Mon Apr 23 10:23:22 CST 2018
     */
    int insert(DefectResourceRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defect_resource_relation
     *
     * @mbg.generated Mon Apr 23 10:23:22 CST 2018
     */
    int insertSelective(DefectResourceRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defect_resource_relation
     *
     * @mbg.generated Mon Apr 23 10:23:22 CST 2018
     */
    List<DefectResourceRelation> selectByExample(DefectResourceRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defect_resource_relation
     *
     * @mbg.generated Mon Apr 23 10:23:22 CST 2018
     */
    int updateByExampleSelective(@Param("record") DefectResourceRelation record, @Param("example") DefectResourceRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defect_resource_relation
     *
     * @mbg.generated Mon Apr 23 10:23:22 CST 2018
     */
    int updateByExample(@Param("record") DefectResourceRelation record, @Param("example") DefectResourceRelationExample example);
}