package wowjoy.fruits.ms.module.relation.mapper;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import wowjoy.fruits.ms.module.relation.entity.ProjectTeamRelation;
import wowjoy.fruits.ms.module.relation.example.ProjectTeamRelationExample;

import java.util.List;

@Mapper
public interface ProjectTeamRelationMapper{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_team_relation
     *
     * @mbg.generated Tue Sep 12 13:20:42 CST 2017
     */
    long countByExample(ProjectTeamRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_team_relation
     *
     * @mbg.generated Tue Sep 12 13:20:42 CST 2017
     */
    int deleteByExample(ProjectTeamRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_team_relation
     *
     * @mbg.generated Tue Sep 12 13:20:42 CST 2017
     */
    int insert(ProjectTeamRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_team_relation
     *
     * @mbg.generated Tue Sep 12 13:20:42 CST 2017
     */
    int insertSelective(ProjectTeamRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_team_relation
     *
     * @mbg.generated Tue Sep 12 13:20:42 CST 2017
     */
    List<ProjectTeamRelation> selectByExample(ProjectTeamRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_team_relation
     *
     * @mbg.generated Tue Sep 12 13:20:42 CST 2017
     */
    int updateByExampleSelective(@Param("record") ProjectTeamRelation record, @Param("example") ProjectTeamRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_team_relation
     *
     * @mbg.generated Tue Sep 12 13:20:42 CST 2017
     */
    int updateByExample(@Param("record") ProjectTeamRelation record, @Param("example") ProjectTeamRelationExample example);
}