package wowjoy.fruits.ms.module.relation.mapper;

import org.apache.ibatis.annotations.Param;
import wowjoy.fruits.ms.module.relation.entity.ProjectListRelation;
import wowjoy.fruits.ms.module.relation.example.ProjectListRelationExample;

import java.util.List;

public interface ProjectListRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_list_relation
     *
     * @mbg.generated Mon Nov 13 10:20:07 CST 2017
     */
    long countByExample(ProjectListRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_list_relation
     *
     * @mbg.generated Mon Nov 13 10:20:07 CST 2017
     */
    int deleteByExample(ProjectListRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_list_relation
     *
     * @mbg.generated Mon Nov 13 10:20:07 CST 2017
     */
    int insert(ProjectListRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_list_relation
     *
     * @mbg.generated Mon Nov 13 10:20:07 CST 2017
     */
    int insertSelective(ProjectListRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_list_relation
     *
     * @mbg.generated Mon Nov 13 10:20:07 CST 2017
     */
    List<ProjectListRelation> selectByExample(ProjectListRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_list_relation
     *
     * @mbg.generated Mon Nov 13 10:20:07 CST 2017
     */
    int updateByExampleSelective(@Param("record") ProjectListRelation record, @Param("example") ProjectListRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_list_relation
     *
     * @mbg.generated Mon Nov 13 10:20:07 CST 2017
     */
    int updateByExample(@Param("record") ProjectListRelation record, @Param("example") ProjectListRelationExample example);
}