package wowjoy.fruits.ms.module.relation.mapper;

import org.apache.ibatis.annotations.Param;
import wowjoy.fruits.ms.module.relation.entity.TaskListRelation;
import wowjoy.fruits.ms.module.relation.example.TaskListRelationExample;

import java.util.List;

public interface TaskListRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_list_relation
     *
     * @mbg.generated Thu Oct 12 17:39:28 CST 2017
     */
    long countByExample(TaskListRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_list_relation
     *
     * @mbg.generated Thu Oct 12 17:39:28 CST 2017
     */
    int deleteByExample(TaskListRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_list_relation
     *
     * @mbg.generated Thu Oct 12 17:39:28 CST 2017
     */
    int insert(TaskListRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_list_relation
     *
     * @mbg.generated Thu Oct 12 17:39:28 CST 2017
     */
    int insertSelective(TaskListRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_list_relation
     *
     * @mbg.generated Thu Oct 12 17:39:28 CST 2017
     */
    List<TaskListRelation> selectByExample(TaskListRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_list_relation
     *
     * @mbg.generated Thu Oct 12 17:39:28 CST 2017
     */
    int updateByExampleSelective(@Param("record") TaskListRelation record, @Param("example") TaskListRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_list_relation
     *
     * @mbg.generated Thu Oct 12 17:39:28 CST 2017
     */
    int updateByExample(@Param("record") TaskListRelation record, @Param("example") TaskListRelationExample example);
}