package wowjoy.fruits.ms.module.relation.mapper;

import org.apache.ibatis.annotations.Param;
import wowjoy.fruits.ms.module.relation.entity.TransferUserRelation;
import wowjoy.fruits.ms.module.relation.example.TransferUserRelationExample;

import java.util.List;

public interface TransferUserRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_user_relation
     *
     * @mbg.generated Fri Mar 09 10:34:37 CST 2018
     */
    long countByExample(TransferUserRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_user_relation
     *
     * @mbg.generated Fri Mar 09 10:34:37 CST 2018
     */
    int deleteByExample(TransferUserRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_user_relation
     *
     * @mbg.generated Fri Mar 09 10:34:37 CST 2018
     */
    int insert(TransferUserRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_user_relation
     *
     * @mbg.generated Fri Mar 09 10:34:37 CST 2018
     */
    int insertSelective(TransferUserRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_user_relation
     *
     * @mbg.generated Fri Mar 09 10:34:37 CST 2018
     */
    List<TransferUserRelation> selectByExample(TransferUserRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_user_relation
     *
     * @mbg.generated Fri Mar 09 10:34:37 CST 2018
     */
    int updateByExampleSelective(@Param("record") TransferUserRelation record, @Param("example") TransferUserRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_user_relation
     *
     * @mbg.generated Fri Mar 09 10:34:37 CST 2018
     */
    int updateByExample(@Param("record") TransferUserRelation record, @Param("example") TransferUserRelationExample example);
}