package wowjoy.fruits.ms.module.relation.mapper;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import wowjoy.fruits.ms.module.relation.entity.UserProjectRelation;
import wowjoy.fruits.ms.module.relation.example.UserProjectRelationExample;

import java.util.List;

@Mapper
public interface UserProjectRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_project_relation
     *
     * @mbg.generated Tue Sep 12 13:20:42 CST 2017
     */
    long countByExample(UserProjectRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_project_relation
     *
     * @mbg.generated Tue Sep 12 13:20:42 CST 2017
     */
    int deleteByExample(UserProjectRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_project_relation
     *
     * @mbg.generated Tue Sep 12 13:20:42 CST 2017
     */
    int insert(UserProjectRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_project_relation
     *
     * @mbg.generated Tue Sep 12 13:20:42 CST 2017
     */
    int insertSelective(UserProjectRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_project_relation
     *
     * @mbg.generated Tue Sep 12 13:20:42 CST 2017
     */
    List<UserProjectRelation> selectByExample(UserProjectRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_project_relation
     *
     * @mbg.generated Tue Sep 12 13:20:42 CST 2017
     */
    int updateByExampleSelective(@Param("record") UserProjectRelation record, @Param("example") UserProjectRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_project_relation
     *
     * @mbg.generated Tue Sep 12 13:20:42 CST 2017
     */
    int updateByExample(@Param("record") UserProjectRelation record, @Param("example") UserProjectRelationExample example);
}