package wowjoy.fruits.ms.module.relation.mapper;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import wowjoy.fruits.ms.module.relation.entity.UserTeamRelation;
import wowjoy.fruits.ms.module.relation.example.UserTeamRelationExample;

import java.util.List;

@Mapper
public interface UserTeamRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_team_relation
     *
     * @mbg.generated Tue Sep 05 16:19:14 CST 2017
     */
    long countByExample(UserTeamRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_team_relation
     *
     * @mbg.generated Tue Sep 05 16:19:14 CST 2017
     */
    int deleteByExample(UserTeamRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_team_relation
     *
     * @mbg.generated Tue Sep 05 16:19:14 CST 2017
     */
    int insert(UserTeamRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_team_relation
     *
     * @mbg.generated Tue Sep 05 16:19:14 CST 2017
     */
    int insertSelective(UserTeamRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_team_relation
     *
     * @mbg.generated Tue Sep 05 16:19:14 CST 2017
     */
    List<UserTeamRelation> selectByExample(UserTeamRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_team_relation
     *
     * @mbg.generated Tue Sep 05 16:19:14 CST 2017
     */
    int updateByExampleSelective(@Param("record") UserTeamRelation record, @Param("example") UserTeamRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_team_relation
     *
     * @mbg.generated Tue Sep 05 16:19:14 CST 2017
     */
    int updateByExample(@Param("record") UserTeamRelation record, @Param("example") UserTeamRelationExample example);
}