package wowjoy.fruits.ms.module.plan.mapper;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import wowjoy.fruits.ms.module.plan.FruitPlanDao;
import wowjoy.fruits.ms.module.plan.example.FruitPlanExample;

import java.util.List;


@Mapper
public interface FruitPlanMapper extends FruitPlanMapperExt {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_plan
     *
     * @mbg.generated Mon Sep 11 17:00:28 CST 2017
     */
    long countByExample(FruitPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_plan
     *
     * @mbg.generated Mon Sep 11 17:00:28 CST 2017
     */
    int deleteByExample(FruitPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_plan
     *
     * @mbg.generated Mon Sep 11 17:00:28 CST 2017
     */
    int insert(FruitPlanDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_plan
     *
     * @mbg.generated Mon Sep 11 17:00:28 CST 2017
     */
    int insertSelective(FruitPlanDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_plan
     *
     * @mbg.generated Mon Sep 11 17:00:28 CST 2017
     */
    List<FruitPlanDao> selectByExampleWithBLOBs(FruitPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_plan
     *
     * @mbg.generated Mon Sep 11 17:00:28 CST 2017
     */
    List<FruitPlanDao> selectByExample(FruitPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_plan
     *
     * @mbg.generated Mon Sep 11 17:00:28 CST 2017
     */
    int updateByExampleSelective(@Param("record") FruitPlanDao record, @Param("example") FruitPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_plan
     *
     * @mbg.generated Mon Sep 11 17:00:28 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") FruitPlanDao record, @Param("example") FruitPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_plan
     *
     * @mbg.generated Mon Sep 11 17:00:28 CST 2017
     */
    int updateByExample(@Param("record") FruitPlanDao record, @Param("example") FruitPlanExample example);
}