package wowjoy.fruits.ms.module.plan.mapper;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import wowjoy.fruits.ms.module.plan.FruitPlanSummary;
import wowjoy.fruits.ms.module.plan.example.FruitPlanSummaryExample;

import java.util.List;

@Mapper
public interface FruitPlanSummaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_plan_summary
     *
     * @mbg.generated Thu Mar 08 15:55:07 CST 2018
     */
    long countByExample(FruitPlanSummaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_plan_summary
     *
     * @mbg.generated Thu Mar 08 15:55:07 CST 2018
     */
    int deleteByExample(FruitPlanSummaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_plan_summary
     *
     * @mbg.generated Thu Mar 08 15:55:07 CST 2018
     */
    int insert(FruitPlanSummary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_plan_summary
     *
     * @mbg.generated Thu Mar 08 15:55:07 CST 2018
     */
    int insertSelective(FruitPlanSummary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_plan_summary
     *
     * @mbg.generated Thu Mar 08 15:55:07 CST 2018
     */
    List<FruitPlanSummary> selectByExample(FruitPlanSummaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_plan_summary
     *
     * @mbg.generated Thu Mar 08 15:55:07 CST 2018
     */
    int updateByExampleSelective(@Param("record") FruitPlanSummary record, @Param("example") FruitPlanSummaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_plan_summary
     *
     * @mbg.generated Thu Mar 08 15:55:07 CST 2018
     */
    int updateByExample(@Param("record") FruitPlanSummary record, @Param("example") FruitPlanSummaryExample example);
}