package wowjoy.fruits.ms.module.user.mapper;

import org.apache.ibatis.annotations.Param;
import wowjoy.fruits.ms.module.user.FruitUser;
import wowjoy.fruits.ms.module.user.FruitUserExample;

import java.util.List;

public interface FruitUserMapper extends FruitUserMapperExt{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_user
     *
     * @mbg.generated Thu Aug 31 16:31:04 CST 2017
     */
    long countByExample(FruitUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_user
     *
     * @mbg.generated Thu Aug 31 16:31:04 CST 2017
     */
    int deleteByExample(FruitUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_user
     *
     * @mbg.generated Thu Aug 31 16:31:04 CST 2017
     */
    int insert(FruitUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_user
     *
     * @mbg.generated Thu Aug 31 16:31:04 CST 2017
     */
    int insertSelective(FruitUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_user
     *
     * @mbg.generated Thu Aug 31 16:31:04 CST 2017
     */
    List<FruitUser> selectByExample(FruitUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_user
     *
     * @mbg.generated Thu Aug 31 16:31:04 CST 2017
     */
    int updateByExampleSelective(@Param("record") FruitUser record, @Param("example") FruitUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_user
     *
     * @mbg.generated Thu Aug 31 16:31:04 CST 2017
     */
    int updateByExample(@Param("record") FruitUser record, @Param("example") FruitUserExample example);
}