package wowjoy.fruits.ms.module.user.mapper;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import wowjoy.fruits.ms.module.user.FruitAccount;
import wowjoy.fruits.ms.module.user.example.FruitAccountExample;

import java.util.List;

@Mapper
public interface FruitAccountMapper extends FruitAccountMapperExt{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_account
     *
     * @mbg.generated Thu Oct 26 16:03:55 CST 2017
     */
    long countByExample(FruitAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_account
     *
     * @mbg.generated Thu Oct 26 16:03:55 CST 2017
     */
    int deleteByExample(FruitAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_account
     *
     * @mbg.generated Thu Oct 26 16:03:55 CST 2017
     */
    int insert(FruitAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_account
     *
     * @mbg.generated Thu Oct 26 16:03:55 CST 2017
     */
    int insertSelective(FruitAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_account
     *
     * @mbg.generated Thu Oct 26 16:03:55 CST 2017
     */
    List<FruitAccount> selectByExampleWithBLOBs(FruitAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_account
     *
     * @mbg.generated Thu Oct 26 16:03:55 CST 2017
     */
    List<FruitAccount> selectByExample(FruitAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_account
     *
     * @mbg.generated Thu Oct 26 16:03:55 CST 2017
     */
    int updateByExampleSelective(@Param("record") FruitAccount record, @Param("example") FruitAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_account
     *
     * @mbg.generated Thu Oct 26 16:03:55 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") FruitAccount record, @Param("example") FruitAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_account
     *
     * @mbg.generated Thu Oct 26 16:03:55 CST 2017
     */
    int updateByExample(@Param("record") FruitAccount record, @Param("example") FruitAccountExample example);
}