spring:
  application:
    name: fruits
  http:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
server:
  port: 8018

pagehelper:
  helper-dialect: mysql
  reasonable: true

security:
  user:
    password: password
  basic:
    enabled: false
#debug: true



tomcat:
  jdbc:
    pool:
      uri: jdbc:mysql://buckball.cn:8306/fruits?useUnicode=true&characterEncoding=utf8&useSSL=false
      password: my-secret-pw
      username: root
      driverClassName: com.mysql.cj.jdbc.Driver