package wowjoy.fruits.ms.module.versions.mapper;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import wowjoy.fruits.ms.module.versions.FruitVersions;
import wowjoy.fruits.ms.module.versions.FruitVersionsExample;

import java.util.List;

@Mapper
public interface FruitVersionsMapper extends FruitVersionsMapperExt {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_versions
     *
     * @mbg.generated Wed Apr 18 10:12:27 CST 2018
     */
    long countByExample(FruitVersionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_versions
     *
     * @mbg.generated Wed Apr 18 10:12:27 CST 2018
     */
    int deleteByExample(FruitVersionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_versions
     *
     * @mbg.generated Wed Apr 18 10:12:27 CST 2018
     */
    int insert(FruitVersions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_versions
     *
     * @mbg.generated Wed Apr 18 10:12:27 CST 2018
     */
    int insertSelective(FruitVersions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_versions
     *
     * @mbg.generated Wed Apr 18 10:12:27 CST 2018
     */
    List<FruitVersions> selectByExample(FruitVersionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_versions
     *
     * @mbg.generated Wed Apr 18 10:12:27 CST 2018
     */
    int updateByExampleSelective(@Param("record") FruitVersions record, @Param("example") FruitVersionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruits_versions
     *
     * @mbg.generated Wed Apr 18 10:12:27 CST 2018
     */
    int updateByExample(@Param("record") FruitVersions record, @Param("example") FruitVersionsExample example);
}