package wowjoy.fruits.ms.module.mark.mapper;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import wowjoy.fruits.ms.module.mark.UserMarkProject;
import wowjoy.fruits.ms.module.mark.UserMarkProjectExample;

import java.util.List;

@Mapper
public interface UserMarkProjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mark_project
     *
     * @mbg.generated Mon Apr 16 17:17:25 CST 2018
     */
    long countByExample(UserMarkProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mark_project
     *
     * @mbg.generated Mon Apr 16 17:17:25 CST 2018
     */
    int deleteByExample(UserMarkProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mark_project
     *
     * @mbg.generated Mon Apr 16 17:17:25 CST 2018
     */
    int insert(UserMarkProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mark_project
     *
     * @mbg.generated Mon Apr 16 17:17:25 CST 2018
     */
    int insertSelective(UserMarkProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mark_project
     *
     * @mbg.generated Mon Apr 16 17:17:25 CST 2018
     */
    List<UserMarkProject> selectByExample(UserMarkProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mark_project
     *
     * @mbg.generated Mon Apr 16 17:17:25 CST 2018
     */
    int updateByExampleSelective(@Param("record") UserMarkProject record, @Param("example") UserMarkProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_mark_project
     *
     * @mbg.generated Mon Apr 16 17:17:25 CST 2018
     */
    int updateByExample(@Param("record") UserMarkProject record, @Param("example") UserMarkProjectExample example);
}